development:
  secret_key_base: 5eb51003bf255d5dcdc5d9fb832729adf294e2e2406c4a51a95bd28b553f82b3b925166c7bbb257e98574077076a2599938f94314d52a2c77071e0aa5257078d
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
edge:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
stable:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
